title: WWI Poster
email: ckness2@illinois.edu
description: by Caroline Kness

baseurl: "/wwiposter" # the subpath of your site. Change it if the name of your repository is other than "mindoc"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
